name: Bug Report 🐛
description: Report a bug or issue with the Discord Voice Timer Bot
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! 
              Please provide as much detail as possible to help us resolve the issue quickly.

    - type: checkboxes
      id: terms
      attributes:
          label: Pre-flight Checklist
          description: Please confirm you have completed these steps
          options:
              - label: I have searched existing issues to ensure this bug hasn't been reported already
                required: true
              - label: I am using the latest version of the bot
                required: true
              - label: I have checked the documentation and troubleshooting guide
                required: true

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: A clear and concise description of what the bug is
          placeholder: "The bot doesn't respond to slash commands..."
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          description: Tell us how to reproduce this behavior
          placeholder: |
              1. Run the command `/stats`
              2. Wait for response
              3. See error message
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: What did you expect to happen?
          placeholder: 'The bot should show voice statistics...'
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: What actually happened?
          placeholder: 'The bot showed an error message...'
      validations:
          required: true

    - type: dropdown
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you running the bot on?
          options:
              - Windows 10
              - Windows 11
              - macOS
              - Ubuntu/Debian
              - CentOS/RHEL
              - Other Linux
              - Docker
      validations:
          required: true

    - type: input
      id: node-version
      attributes:
          label: Node.js Version
          description: What version of Node.js are you using?
          placeholder: '18.17.0'
      validations:
          required: true

    - type: input
      id: bot-version
      attributes:
          label: Bot Version
          description: What version of the bot are you using?
          placeholder: '1.2.0'
      validations:
          required: true

    - type: textarea
      id: logs
      attributes:
          label: Error Logs
          description: Please copy and paste any relevant log output
          render: shell
          placeholder: |
              🔍 [14:30:45] Revisando canales de voz...
              ❌ Error: ...

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots
          description: If applicable, add screenshots to help explain your problem
          placeholder: 'Drag and drop images here or paste links'

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context about the problem here
          placeholder: 'This started happening after...'
