# Docker Compose for Production
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  discord-bot:
    # Pre-built image (optional, for CI/CD)
    # image: ghcr.io/danoglez/discord-voice-timer-bot:latest
    
    # Stricter production configuration
    environment:
      - NODE_ENV=production
    
    # More aggressive restart policy
    restart: always
    
    # Stricter resource limits
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Production-optimized logging
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    
    # More frequent healthcheck
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
