name: CI/CD Pipeline

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master]

env:
    NODE_VERSION: '18'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Run tests
              run: npm test

            - name: Check code formatting
              run: npm run format:check

    security:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run security audit
              run: npm audit --audit-level=moderate

            - name: Check for vulnerabilities
              run: npx better-npm-audit audit

    validate-config:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Validate configuration files
              run: |
                  node -e "require('./config.js')"
                  echo "✅ Configuration validation passed"

            - name: Check required environment variables
              run: |
                  if [ ! -f .env.example ]; then
                    echo "❌ .env.example file missing"
                    exit 1
                  fi
                  echo "✅ Environment configuration files present"

    build-check:
        runs-on: ubuntu-latest
        needs: [test, security, validate-config]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Dry run bot startup
              run: |
                  timeout 10s npm start || code=$?
                  if [[ $code -ne 124 && $code -ne 0 ]]; then
                    echo "❌ Bot failed to start properly"
                    exit 1
                  fi
                  echo "✅ Bot startup validation passed"
              env:
                  DISCORD_TOKEN: 'fake_token_for_testing'
                  NODE_ENV: 'test'
